services:
  redis:
    image: redislabs/redismod
    container_name: skybooker_redis_container
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15
    container_name: skybooker_postgres_container
    environment:
      POSTGRES_DB: skybooker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

      
  skybooker:
    container_name: skybooker_appserver
    build:
      context: .
      target: builder
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://postgres:5432/skybooker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      REDIS_HOST:  redis
      REDIS_PORT:  6379
    depends_on:
       postgres:
        condition : service_healthy
       redis:
        condition: service_healthy
    volumes:
      - .:/code

volumes:
  pgdata: