services:
  redis:
    image: redislabs/redismod
    container_name: skybooker_redis_container
    ports:
      - '6379:6379'

  postgres:
    image: postgres:15
    container_name: skybooker_postgres_container
    environment:
      POSTGRES_DB: skybooker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
#  skybooker:
#    container_name: skybooker_appserver
#    build:
#      context: .
#      target: builder
#    ports:
#      - '8080:8080'
#    environment:
#      SPRING_DATASOURCE_URL:  jdbc:postgresql://postgres:5432/skybooker
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#      REDIS_HOST:  redis
#      REDIS_PORT:  6379
#    depends_on:
#      - postgres
#      - redis
#    volumes:
#      - .:/code

volumes:
  pgdata:
  prom_data: