version: '3.8'

services:
  redis:
    image: redislabs/redismod
    container_name: skybooker_redis_container
    ports:
      - '6379:6379'

  postgres:
    image: postgres:15
    container_name: skybooker_postgres_container
    environment:
      POSTGRES_DB: skybooker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
